# Generated by Django 3.0.4 on 2020-03-31 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidateFirstName', models.CharField(max_length=100, null=True)),
                ('candidateLastName', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phoneNo', models.BigIntegerField()),
                ('address', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('zip', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('candidateCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatecategoryname', to='Core.CandidateCategory')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidateownername', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phoneNo', models.BigIntegerField()),
                ('address', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('zip', models.CharField(blank=True, max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownername', to=settings.AUTH_USER_MODEL)),
                ('sponsorGroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorgroupname', to='Core.SponsorGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donationName', models.CharField(max_length=50)),
                ('donationDescription', models.TextField(blank=True)),
                ('donationDate', models.DateTimeField()),
                ('donationAmount', models.FloatField(blank=True)),
                ('donationBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_name', to='Core.Sponsors')),
                ('donationTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_name', to='Core.Candidates')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donationownername', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docName', models.CharField(max_length=100)),
                ('docType', models.CharField(max_length=30)),
                ('docContent', models.TextField(blank=True)),
                ('lastEdited', models.DateTimeField(auto_now_add=True)),
                ('isTemplate', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='candidates',
            name='sponsorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsoridname', to='Core.Sponsors'),
        ),
    ]
