# Generated by Django 3.0.4 on 2020-03-31 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidates',
            old_name='candidateFirstName',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='candidates',
            old_name='candidateLastName',
            new_name='lastName',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='sponsorId',
        ),
        migrations.AddField(
            model_name='candidates',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorName', to='Core.Sponsors'),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='candidateCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidateCategoryName', to='Core.CandidateCategory'),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidateOwnerName', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donations',
            name='donationBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donSponsorName', to='Core.Sponsors'),
        ),
        migrations.AlterField(
            model_name='donations',
            name='donationTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donCandidateName', to='Core.Candidates'),
        ),
        migrations.AlterField(
            model_name='donations',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donationOwnerName', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorOwnerName', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='sponsorGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorGroupName', to='Core.SponsorGroup'),
        ),
    ]
