# Generated by Django 3.0.4 on 2020-04-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20200331_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidates',
            old_name='created_at',
            new_name='createdAt',
        ),
    ]
