# Generated by Django 3.0.4 on 2020-04-05 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20200403_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='documents',
            name='docType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentType', to='Core.DocumentTypes'),
        ),
    ]
