# Generated by Django 3.0.4 on 2020-04-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20200405_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='phoneNo',
            field=models.CharField(max_length=15),
        ),
    ]
