# Generated by Django 3.0.4 on 2020-04-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_auto_20200410_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsors',
            name='phoneNo',
            field=models.CharField(max_length=15),
        ),
    ]
